#!/usr/bin/env python

import argparse
import requests
from nvchecker import core as nvchecker_core


def main():
    parser = argparse.ArgumentParser(description='Update nvchecker newver db with data from deepin-code-release')
    parser.add_argument('nvchecker_config', metavar='NVCHECKER_CONFIG', type=open,
                        help='nvchecker configuration file')
    parser.add_argument('--branch', metavar="BRANCH", default="panda/current", required=False,
                        help="deepin-code-review branch to use (default: panda/current)")
    args = parser.parse_args()

    source = nvchecker_core.Source(args.nvchecker_config)
    if source.oldver:
        source.oldvers = nvchecker_core.read_verfile(source.oldver)
    else:
        source.oldvers = {}

    if source.newver:
        source.newvers = nvchecker_core.read_verfile(source.newver)
    else:
        source.newvers = {}

    source.curvers = source.oldvers.copy()

    dcr_versions = requests.get("https://raw.githubusercontent.com/linuxdeepin/deepin-code-release/%s/project_list.json" % args.branch).json()
    dcr_updates = {}
    for project in dcr_versions:
        if project in source.oldvers:
            dcr_updates[project] = dcr_versions[project]["tag"]
        elif "python-" + project in source.oldvers:
            dcr_updates["python-" + project] = dcr_versions[project]["tag"]
        elif "deepin-" + project in source.oldvers:
            dcr_updates["deepin-" + project] = dcr_versions[project]["tag"]
        elif project.replace("dde-", "deepin-") in source.oldvers:
            dcr_updates[project.replace("dde-", "deepin-")] = dcr_versions[project]["tag"]
        elif project.replace("go-", "deepin-") in source.oldvers:
            dcr_updates[project.replace("go-", "deepin-")] = dcr_versions[project]["tag"]

    for pkg in dcr_updates:
        print(pkg, dcr_updates[pkg])

    source.newvers.update(dcr_updates)
    nvchecker_core.write_verfile(source.newver, source.newvers)


if __name__ == '__main__':
    main()
