#!/bin/sh
hkgname=$1
ver1=$2
ver2=$3

wget -O /tmp/$hkgname.cabal1 https://hackage.haskell.org/package/$hkgname-$ver1/$hkgname.cabal
wget -O /tmp/$hkgname.cabal2 https://hackage.haskell.org/package/$hkgname-$ver2/$hkgname.cabal

git diff --ignore-space-change --ignore-blank-lines --text /tmp/$hkgname.cabal1 /tmp/$hkgname.cabal2
