#!/bin/bash
cpanname=$1
ver1=$2
ver2=$3

author=$(curl https://fastapi.metacpan.org/release/$cpanname | jq -r .author)

# TODO: how to fetch old author?
oldauthor=$4

[[ -z "$oldauthor" ]] && oldauthor=author

test -f /tmp/$cpanname.json.$ver1 || curl https://fastapi.metacpan.org/release/$oldauthor/$cpanname-$ver1 | jq -S '.release.dependency | sort | .[] | .module, .phase' > /tmp/$cpanname.json.$ver1
test -f /tmp/$cpanname.json.$ver2 || curl https://fastapi.metacpan.org/release/$author/$cpanname-$ver2 | jq -S '.release.dependency | sort | .[] | .module, .phase' > /tmp/$cpanname.json.$ver2

git diff --ignore-space-change --ignore-blank-lines --text /tmp/$cpanname.json.$ver1 /tmp/$cpanname.json.$ver2
