#!/bin/bash

source /usr/share/makepkg/util/message.sh
colorize

# === Handle server & multiple logins ===
_buildserver=$1

# BUILDHOST shall not contain any numbers
BUILDHOST=${_buildserver//[0-9]/}
_login=${_buildserver//[a-zA-Z.@]/}

msg "Building on ${BUILDHOST##*@}"
shift

# === Deal with multiple logins (for parallel building) ===
if [[ -z "$_login" ]]; then
  _cmd="$@"
else
  _cmd=
  _login="-l $USER$_login"
  _mark=
  for _part in "$@"; do
    _cmd="$_cmd $_part"
    if [[ -z "$_mark" && "$_part" == "--" ]]; then
      _cmd="$_cmd $_login"
      _mark=1
    fi
  done
  if [[ -z "$_mark" ]]; then
    _cmd="$_cmd -- $_login"
  fi
fi

# === Sync package to remote host ===
# Prefer to use rsync here because it's much faster than source packages
# makepkg -Sf --skipchecksums --skippgpcheck || exit 1
# SRCPKG=$(ls *.src.tar.gz)
PKGNAME=$(source PKGBUILD; [[ -z $pkgbase ]] && echo $pkgname || echo $pkgbase)
ARCH=$(source PKGBUILD; echo $arch)
msg "Checking for remote environment..."
ssh $BUILDHOST "mkdir -p packages; test -e .makepkg.conf" || exit 1
msg "Syncing package to remote host..."
rsync -avzzP ./ $BUILDHOST:packages/$PKGNAME/ --exclude=*.src.tar* --exclude=*.pkg.tar* --exclude=src/ --exclude=pkg/ --exclude=.git/ || exit 1

# === Handle validpgpkeys ===
if [[ -n "$(. PKGBUILD; echo $validpgpkeys)" && ! "$_cmd" == *"--skippgpcheck"* ]]; then
  msg "Ensuring required PGP keys are present..."
  for _key in $(source PKGBUILD; echo "${validpgpkeys[@]}" 2>/dev/null); do
    msg2 "Checking for $_key..."
    if ! ssh $BUILDHOST "gpg --recv-keys $_key || gpg --fingerprint $_key"; then
      if [[ -f keys/pgp/$_key.asc ]]; then
        msg2 "Importing key from local..."
        ssh $BUILDHOST "gpg --import packages/$PKGNAME/keys/pgp/$_key.asc"
      else
        error "Failed to locate key $_key"
        exit 1
      fi
    fi
  done
fi

# Try to fetch logs
fetch_logs() {
  PKGPREFIX=$(source PKGBUILD; echo $PKGNAME-$epoch${epoch:+:}$pkgver-$pkgrel)
  rsync -avzz $BUILDHOST:packages/$PKGNAME/$PKGPREFIX-*.log ./
}
trap fetch_logs EXIT

# === Handle riscv64 patches ===
if [[ "$1" =~ riscv ]]; then
  . /usr/local/bin/riscvenv
  if [[ -d "$RVPATCHREPO/$PKGNAME" ]]; then
    msg "Applying RISC-V patches..."
    rsync -avzzP $RVPATCHREPO/$PKGNAME/ $BUILDHOST:packages/$PKGNAME/
    if [[ -e "$RVPATCHREPO/$PKGNAME/riscv64.patch" ]]; then
      ssh $BUILDHOST "cd packages/$PKGNAME && patch -p0 -i riscv64.patch" || exit 1
      ARCH=$(ssh $BUILDHOST "cd packages/$PKGNAME; source PKGBUILD; echo \$arch")
    fi
  fi
  if [[ ! "$ARCH" =~ any ]]; then
    msg 'Patching arch to riscv64...'
    ssh $BUILDHOST "echo -e '\narch=(riscv64)' >> packages/$PKGNAME/PKGBUILD" || exit 1
  fi

  # Handle cachedir
  _HOME="$(ssh $BUILDHOST 'mkdir -p $HOME/packages/riscv64-pkg-cache; echo $HOME')"
  _oldcmd="$_cmd"
  _cmd=
  _cachedir="-d $_HOME/packages/riscv64-pkg-cache:/var/cache/pacman/pkg"
  _mark=
  for _part in $_oldcmd; do
    _cmd="$_cmd $_part"
    if [[ -z "$_mark" && "$_part" == "--" ]]; then
      _cmd="$_cmd $_cachedir"
      _mark=1
    fi
  done
  if [[ -z "$_mark" ]]; then
    _cmd="$_cmd -- $_cachedir"
  fi
fi

# === Build the package ===
msg "Running $_cmd on remote host..."
ssh -tt $BUILDHOST "cd packages/$PKGNAME && rm -f *.pkg.tar.*; $_cmd" || exit 1

# === Sync back artifacts ===
msg "Syncing back built packages..."
rsync -avzzP $BUILDHOST:packages/$PKGNAME/*.pkg.tar.* ./ || exit 1

# === Sync back PKGBUILD ===
if [[ -n "$SYNCBACKPKGBUILD" ]]; then
  msg "Syncing back PKGBUILD..."
  rsync -avzzP $BUILDHOST:packages/$PKGNAME/PKGBUILD ./ || exit 1
fi
