#!/usr/bin/python
import os
import pyalpm
import sys
import tempfile


db_fullpath = sys.argv[1]
db_filename = db_fullpath.split("/")[-1]
db = db_filename.split('.')[0]

package = sys.argv[2]

field = sys.argv[3]


with tempfile.TemporaryDirectory() as d:
    os.mkdir(d + "/sync")
    os.symlink(os.path.abspath(db_fullpath), f"{d}/sync/{db_filename}")
    handle = pyalpm.Handle(".", d)
    db_handle = handle.register_syncdb(db, 0)
    pkg = db_handle.get_pkg(package)
    if pkg is None:
        sys.exit("Package not found in repo.")
    print(getattr(pkg, field))
