#!/usr/bin/env python

import os
import csv
from io import StringIO
from sh import pacman
import requests

# Preset: "arch pkgname": "hackage package name"
PRESET_PACKAGES = {
    "alex": "alex",
    "c2hs": "c2hs",
    "cabal-install": "cabal-install",
    "darcs": "darcs",
    "git-annex": "git-annex",
    "gtk2hs-buildtools": "gtk2hs-buildtools",
    "haddock": "haddock",
    "happy": "happy",
    "haskell-dav": "DAV",
    "haskell-gtk": "gtk3",
    "haskell-graphscc": "GraphSCC",
    "haskell-http": "HTTP",
    "haskell-hunit": "HUnit",
    "haskell-ifelse": "IfElse",
    "haskell-missingh": "MissingH",
    "haskell-monadrandom": "MonadRandom",
    "haskell-quickcheck": "QuickCheck",
    "haskell-safesemaphore": "SafeSemaphore",
    "haskell-sha": "SHA",
    "haskell-src-exts": "haskell-src-exts",
    "haskell-statevar": "StateVar",
    "haskell-stmonadtrans": "STMonadTrans",
    "haskell-juicypixels": "JuicyPixels",
    "hasktags": "hasktags",
    "shellcheck": "ShellCheck",
    "xmobar": "xmobar",
    "xmonad": "xmonad",
    "xmonad-contrib": "xmonad-contrib",
}

URL_PATTERN = "https://www.archlinux.org/packages/community/x86_64/%(pkgname)s"

result_fd = StringIO()
result_csv = csv.writer(result_fd, quoting=csv.QUOTE_ALL)
counter = 0

for line in pacman("-Sl", "community", "--color=never"):
    found = False

    # Fetch package and version
    package, version = line.split()[1:3]

    # Remove pkgrel
    version = version.split("-")[0]

    if package in PRESET_PACKAGES:
        found = [PRESET_PACKAGES[package], version]
    elif package.startswith("haskell-"):
        found = [package[8:], version]

    if found:
        print("Found", *found)
        found.append(URL_PATTERN % {"pkgname": package})
        result_csv.writerow(found)

        counter += 1

result_fd.seek(0)
result_body = result_fd.read().rstrip("\r\n")

print(counter, "packages found.")

if "HACKAGE_USERNAME" in os.environ and "HACKAGE_PASSWORD" in os.environ:
    URL = "https://hackage.haskell.org/distro/Arch/packages"
    r = requests.put(
        URL,
        data=result_body,
        auth=(os.environ["HACKAGE_USERNAME"], os.environ["HACKAGE_PASSWORD"]),
        headers={"Content-Type": "text/csv"},
    )
    print("Upload:", r.status_code, r.text)

else:
    print("Please make sure you have HACKAGE_USERNAME and HACKAGE_PASSWORD set to upload the package list.")
