#!/usr/bin/ruby
require 'json'
require 'open-uri'
require 'pycall/import'
require 'set'

include PyCall::Import

pyimport :pyalpm

pkg = ARGV[0]
name_preset = JSON.load(URI.open("https://github.com/berberman/arch-hs/raw/master/data/NAME_PRESET.json"))

archpkg = name_preset.key(pkg) || "haskell-#{pkg}"

handle = pyalpm.Handle.new(".", "/var/lib/pacman")

rdeps = Set[]

["community"].each { |db|
    db_handle = handle.register_syncdb(db, 0)
    db_handle.search("").each { |package|
        ["depends", "makedepends", "checkdepends"].each { |field|
            rdeps << [package.name, package.version.split("-")[0]] if package.send(field).include? archpkg
        }
    }
}

rdeps.each { |rdep, ver|
    puts "Extracting #{rdep}..."
    hackage_name = name_preset[rdep] || rdep[8..-1]
    begin
        cabal = URI.open("https://hackage.haskell.org/package/#{hackage_name}-#{ver}/revision/0.cabal").readlines
        cabal.each { |line|
            puts line if line.include? pkg
        }
    rescue OpenURI::HTTPError
        puts "Failed to fetch #{hackage_name}-#{ver}, ignoring..."
    end
}
