#!/usr/bin/ruby
require 'http'
require 'pycall/import'
require 'set'

include PyCall::Import

pyimport :pyalpm

pkg = ARGV[0]
name_preset = HTTP.follow.get("https://github.com/berberman/arch-hs/raw/master/data/NAME_PRESET.json").parse(:json)

archpkg = name_preset.key(pkg) || "haskell-#{pkg}"

handle = pyalpm.Handle.new(".", "/var/lib/pacman")

rdeps = Set[]

["community"].each { |db|
    db_handle = handle.register_syncdb(db, 0)
    db_handle.search("").each { |package|
        ["depends", "makedepends", "checkdepends"].each { |field|
            rdeps << [package.name, package.version.split("-")[0]] if package.send(field).include? archpkg
        }
    }
}

rdeps.each { |rdep, ver|
    puts "Extracting #{rdep}..."
    hackage_name = name_preset[rdep] || rdep[8..-1]
    cabal = HTTP.get("https://hackage.haskell.org/package/#{hackage_name}-#{ver}/revision/0.cabal")
    puts "Failed to fetch #{hackage_name}-#{ver}, ignoring..." or next if !cabal.status.success?
    cabal.to_s.each_line { |line|
        puts line if line.include? pkg
    }
}
