#!/usr/bin/ruby

require 'set'

def `(cmd)
  system(cmd)
end

pkgs = Set.new(ARGV.filter{|pkg| ! pkg.end_with? ":nocheck"})

# `ssh repos.archlinux.org /packages/db-move extra-staging extra "#{pkgs.join(" ")}"`
`pkgctl db move extra-staging extra #{pkgs.join(" ")}`
