#!/bin/bash

. /usr/local/bin/riscvenv

REPO=$1
PKG=$2

VERSION=$(ssh $TIER0SERVER find-package-in-db-file $TIER0PATH/repo/$REPO/$REPO.db $PKG version)

ssh -t $TIER0SERVER "cd $TIER0PATH/repo/$REPO/; flock /tmp/riscv-repo-$REPO.lck repo-remove $REPO.db.tar.gz $PKG"

if ssh $TIER0SERVER [[ -e "$TIER0PATH/repo/$REPO/$PKG-$VERSION-riscv64.pkg.tar.zst" ]]; then
    ssh $TIER0SERVER rm -v "$TIER0PATH/repo/$REPO/$PKG-$VERSION-riscv64.pkg.tar.zst"{,.sig}
elif ssh $TIER0SERVER [[ -e "$TIER0PATH/repo/$REPO/$PKG-$VERSION-any.pkg.tar.zst" ]]; then
    ssh $TIER0SERVER rm -v "$TIER0PATH/repo/$REPO/$PKG-$VERSION-any.pkg.tar.zst"{,.sig}
else
    echo "Failed to clean up package file. Do it manually!"
fi

# flock ../$1.lck rsync -avP --delete $RVREPO/$1/ $TIER0SERVER/repo/$1/
