#!/usr/bin/ruby

require 'set'
require 'tmpdir'
require 'fileutils'
require 'net/http'
require 'uri'
require 'json'
require 'erb'
require 'pycall/import'

include PyCall::Import

pyimport :pyalpm

REPOROOT = "/var/www/archlinuxriscv"
PATCHREPO = "/var/www/archriscv-packages"

$x86_packages = Hash.new{|h,k| h[k] = {}}
$rv_packages = Hash.new{|h,k| h[k] = {}}
$x86_pkgnames_by_pkgbase = Hash.new{|h,k| h[k] = Set[]}
$x86_depnames_by_pkgbase = Hash.new{|h,k| h[k] = Set[]}
$x86_pkgbase_by_depname = {}

$rv_provides = Set[]
$rv_required_by_depname = Hash.new{|h,k| h[k] = Set[]}
$current_rv_package_mtimes_by_pkgbase = Hash.new{|h,k| h[k] = []}

$outdated_log_pkgbases = Set[]
$version_mismatch_pkgbases = Set[]
$version_mismatch_pkgnames = Set[]
$blacklist = Set[]
$broken_pkgbases = Set[]
$broken_pkgnames = Set[]

STDOUT.sync = true
puts "Running pacman -Sy..."
`pacman -Sy`

puts "Reading blacklist..."
`cd #{PATCHREPO}; git pull`
File.read(PATCHREPO + "/blacklist.txt").each_line do |pkg|
    pkg.chomp!
    next if pkg.start_with? "#" or pkg == ""
    $blacklist << pkg
end

puts "Fetching from MelonBot..."
begin
    $marks = JSON.parse(Net::HTTP.get(URI("https://plct-arv.jiejiss.com/pkg")))["markList"].map do |pkg|
        [pkg["name"], pkg ]
    end.to_h
rescue => e
    puts "Failed to fetch from MelonBot: #{e}"
    $marks = {}
end

File.open("#{REPOROOT}/.status/status.htm.tmp", 'w') do |f|
    f.puts('
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <link rel="stylesheet" href="https://cdnjs.snrat.com/ajax/libs/bulma/1.0.3/css/bulma.min.css" integrity="sha384-DtLgkgZWuBalGogBkye1PTBvXKCD/hnA8vHqpqfcGCf/FOa1heAyeHExO8JNtVM/" crossorigin="anonymous">
    <meta name="htmx-config" content=\'{"selfRequestsOnly":false}\'>
    <script src="https://cdnjs.snrat.com/ajax/libs/htmx/2.0.7/htmx.min.js" integrity="sha384-ZBXiYtYQ6hJ2Y0ZNoYuI+Nq5MqWBr+chMrS/RkXpNzQCApHEhOt2aY8EJgqwHLkJ" crossorigin="anonymous"></script>
    <style>
    .tag.tag-with-details { height: auto; min-height: 2em; }
    .commit-loader a { color: var(--bulma-link-light); }
    .commit-loader ul { margin-left: 0.75em; }
    .commit-loader.htmx-request { pointer-events: none; opacity: 0.7; }
    </style>
    ')

    f.puts(<<~'HTML')
    <script>
    const escapeHTML = (value) => String(value).replace(/[&<>"']/g, (char) => ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        "\"": "&quot;",
        "'": "&#39;"
    }[char]));

    document.addEventListener("htmx:afterRequest", function (event) {
        const tag = event.detail.elt;
        if (!tag || !tag.classList.contains("commit-loader")) {
            return;
        }

        const xhr = event.detail.xhr;
        if (xhr.status < 200 || xhr.status >= 300) {
            tag.innerHTML = "GitLab: HTTP " + xhr.status;
            return;
        }

        try {
            const data = JSON.parse(xhr.responseText);
            const commits = Array.isArray(data.commits) ? data.commits : [];

            if (data.message) {
                tag.innerHTML = "GitLab: " + escapeHTML(data.message);
            } else if (commits.length === 0) {
                tag.innerHTML = "No commits";
            } else {
                tag.innerHTML = "Changes: <ul>" + commits.map(function(commit) {
                    const title = escapeHTML(commit.title || commit.message || commit.id || "commit");
                    const shortId = commit.short_id ? "<span class=\"commit-meta\">" + escapeHTML(commit.short_id) + "</span> " : "";
                    const url = escapeHTML(commit.web_url || "#");
                    return "<li>" + shortId + "<a href=\"" + url + "\">" + title + "</a></li>";
                }).join("") + "</ul>";
            }
        } catch (error) {
            tag.innerHTML = "GitLab: failed to parse response";
        }
    });
    </script>
    HTML

    f.puts('
    <table class="table is-hoverable">
    <thead><tr><th>DB</th><th>Pkgbase</th><th>Status</th></tr></thead><tbody>
    ')

    if $marks.empty?
        f.puts("<tr><td></td><td>_warning</td><td><span style='color:var(--bulma-danger)'>Failed to fetch from MelonBot, marks will be missing!</span></td></tr>")
    end

    def read_db(handle, db, result)
        count = 0
        db_handle = handle.register_syncdb(db, 0)
        db_handle.search("").each do |package|
            yield package

            ["depends", "makedepends", "checkdepends", "provides", "arch", "base", "version", "filename"].each do |field|
                result[package.name][field] = package.send(field)
            end
            result[package.name]["db"] = db

            count += 1
        end

        count
    end

    puts "Faking sync database..."
    Dir.mktmpdir do |dir|
        Dir.mkdir("#{dir}/sync")
        ["core", "extra"].each do |db|
            FileUtils.ln_s("#{REPOROOT}/repo/#{db}/#{db}.db", "#{dir}/sync/")
        end

        x86_handle = pyalpm.Handle.new(".", "/var/lib/pacman")
        rv_handle = pyalpm.Handle.new(".", "#{dir}")

        stat = ""
        ["core", "extra"].each do |db|
            puts "Reading x86_64 #{db}..."
            x86_count = read_db(x86_handle, db, $x86_packages) do |package|
                $x86_pkgnames_by_pkgbase[package.base] << package.name
                $x86_depnames_by_pkgbase[package.base] << package.name
                $x86_pkgbase_by_depname[package.name] = package.base
                package.provides.each do |_package|
                    depname = _package.split("=")[0]
                    $x86_depnames_by_pkgbase[package.base] << depname
                    $x86_pkgbase_by_depname[depname] ||= package.base
                end
            end

            puts "Reading riscv64 #{db}..."
            rv_count = read_db(rv_handle, db, $rv_packages) do |package|
                if ! File.exist?("#{REPOROOT}/repo/#{db}/#{package.filename}")
                    f.puts("<tr><td>#{db}</td><td>#{package.base}</td><td><span style='color:var(--bulma-danger)'>Lint: #{package.name} package file not found in repository</span></td></tr>")
                elsif ! File.exist?("#{REPOROOT}/repo/#{db}/#{package.filename}.sig")
                    f.puts("<tr><td>#{db}</td><td>#{package.base}</td><td><span style='color:var(--bulma-danger)'>Lint: #{package.name} package signature not found in repository</span></td></tr>")
                end

                if $rv_packages.has_key?(package.name)
                    f.puts("<tr><td>#{db}</td><td>#{package.base}</td>
                                <td><span style='color:var(--bulma-danger)'>Lint: #{package.name} found in different repository: #{$rv_packages[package.name]['db']}.
                                x86 repo: #{$x86_packages[package.name]['db']}</span></td></tr>")
                end
            end

            percent = (rv_count * 100.0 / x86_count).round(2)
            stat += "[#{db}] #{rv_count} / #{x86_count} (#{percent}%)\n"
        end

        puts "Writing status.txt..."
        File.open("#{REPOROOT}/.status/status.txt.tmp", 'w') do |f|
            f.puts(stat)
        end
        File.rename("#{REPOROOT}/.status/status.txt.tmp", "#{REPOROOT}/.status/status.txt")
    end

    $rv_provides |= $rv_packages.keys.to_set

    puts "Indexing riscv reverse dependencies..."
    $rv_packages.each do |pkgname, package|
        package["depends"].each do |dep|
            $rv_required_by_depname[dep.split(/[<>=]/)[0]] << pkgname
        end
    end

    puts "Checking version mismatch..."
    $rv_packages.each do |pkgname, package|
        rvver = package["version"]

        if rvver.split("-")[1].include? "."
            rvver = [rvver.split("-")[0], rvver.split("-")[1].split(".")[0]].join("-")
        end

        if $x86_packages.has_key?(pkgname) && $x86_packages[pkgname]["version"] == rvver
            pkgfile = "#{REPOROOT}/repo/#{package['db']}/#{package['filename']}"
            $current_rv_package_mtimes_by_pkgbase[$x86_packages[pkgname]["base"]] << File.mtime(pkgfile) if File.exist?(pkgfile)
        end

        if $x86_packages.has_key?(pkgname) && $x86_packages[pkgname]["version"] != rvver
            $version_mismatch_pkgbases << $x86_packages[pkgname]["base"]
            $version_mismatch_pkgnames << pkgname
            package['provides'].each do |_package|
                depname = _package.split("=")[0]
                $version_mismatch_pkgnames << depname if ! $x86_packages.has_key? depname
            end
        end

        package["provides"].each do |_package|
            $rv_provides << _package.split("=")[0]
        end
    end

    def arch_gitlab_tag(version)
        tag = version.sub(":", "-")
        pkgver, sep, pkgrel = tag.rpartition("-")
        return tag if sep.empty?

        "#{pkgver}-#{pkgrel.split(".")[0]}"
    end

    def arch_gitlab_compare_url(pkgbase, from_version, to_version)
        project = URI.encode_www_form_component("archlinux/packaging/packages/#{pkgbase}")
        params = URI.encode_www_form({
            "from" => arch_gitlab_tag(from_version),
            "to" => arch_gitlab_tag(to_version),
            "straight" => "true",
        })
        "https://gitlab.archlinux.org/api/v4/projects/#{project}/repository/compare?#{params}"
    end

    def patch_repo_link(pkgbase)
        if File.exist?("#{PATCHREPO}/#{pkgbase}")
            " <a href=https://github.com/felixonmars/archriscv-packages/tree/master/#{pkgbase}>
              <span class='tag is-info'>patched</span></a>"
        else
            ""
        end
    end

    def parse_build_log(log)
        cached_stage_file = File.dirname(log) + "/." + File.basename(log) + ".failed_stage"
        if File.exist?(cached_stage_file) and File.mtime(cached_stage_file) > File.mtime(log)
            return File.read(cached_stage_file).chomp
        end
        puts "Parsing build log #{log}..."
        stages = [
            ["patch failed", "\x1b[1m\x1b[32m==>\x1b[m\x0f\x1b[1m Applying RISC-V patches...\x1b[m\x0f"],
            ["source download failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m Failure while downloading"],
            ["checksum mismatch", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m One or more files did not pass the validity check"],
            ["gpg failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m One or more PGP signatures"],
            ["dependency missing", "\x1b[?25h\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m Could not resolve all dependencies"],
            ["dependency missing", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m Could not resolve all dependencies."],
            ["prepare() failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m A failure occurred in prepare()."],
            ["build() failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m A failure occurred in build()."],
            ["check() failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m A failure occurred in check()."],
            ["package() failed", "\x1b[1m\x1b[31m==> ERROR:\x1b[m\x0f\x1b[1m A failure occurred in package"],
            ["old config.guess", "configure: error: cannot guess build type; you must specify one"],
            ["broken rust target", "  error: Error loading target specification: Could not find specification for target \"riscv64-unknown-linux-gnu\"."],
        ]
        last_failed_stage = nil
        File.read(log).each_line do |line|
            stages.each do |stage, prefix|
                if line.start_with?(prefix)
                    last_failed_stage = stage
                    # Only check stages after the last failed stage for the following lines
                    stages.dup.each do |stage, prefix|
                        stages.delete [stage, prefix]
                        if stage == last_failed_stage
                            break
                        end
                    end
                end
            end
        end
        File.write(cached_stage_file, last_failed_stage) if last_failed_stage
        last_failed_stage
    end

    puts "Checking broken packages..."
    old_log_threshold = Time.now - 30 * 24 * 60 * 60
    $nocheck_pkgbases = Set[]
    $x86_packages.each do |pkgname, package|
        if File.exist?("#{REPOROOT}/.status/logs/#{package['base']}")
            if $rv_packages.has_key?(pkgname)
                rvver = $rv_packages[pkgname]["version"]
                if File.exist?("#{REPOROOT}/.status/logs/#{package['base']}/.nocheck")
                    nocheckver = File.read("#{REPOROOT}/.status/logs/#{package['base']}/.nocheck").chomp
                    if nocheckver == rvver
                        $nocheck_pkgbases << package['base']
                    end
                end

                if rvver.split("-")[1].include? "."
                    rvver = [rvver.split("-")[0], rvver.split("-")[1].split(".")[0]].join("-")
                end

                next if rvver == package["version"]
            end

            log_mtime = nil
            if File.exist?("#{REPOROOT}/.status/logs/#{package['base']}/#{package['base']}-#{package['version']}.log")
                log_mtime = File.mtime("#{REPOROOT}/.status/logs/#{package['base']}/#{package['base']}-#{package['version']}.log")
            elsif Dir.glob("#{REPOROOT}/.status/logs/#{package['base']}/#{package['base']}-#{package['version']}-*.log").any?
                log_mtime = Dir.glob("#{REPOROOT}/.status/logs/#{package['base']}/#{package['base']}-#{package['version']}-*.log").map{|log| File.mtime(log)}.max
            else
                $outdated_log_pkgbases << package['base']
                next
            end
            next if $current_rv_package_mtimes_by_pkgbase[package['base']].any?{|mtime| mtime > log_mtime}

            $broken_pkgbases << package['base']
            $broken_pkgnames << pkgname
            package['provides'].each do |_package|
                depname = _package.split("=")[0]
                $broken_pkgnames << depname if ! $x86_packages.has_key? depname
            end
        end
    end

    def missing_dep(pkgbase)
        def check_dep(pkgbase)
            $x86_pkgnames_by_pkgbase[pkgbase].each do |pkgname|
                next if ! $x86_packages.has_key? pkgname
                package = $x86_packages[pkgname]
                package["depends"].each do |dep| yield [dep, nil] end
                package["makedepends"].each do |dep| yield [dep, "make"] end
                package["checkdepends"].each do |dep| yield [dep, "check"] end
            end
        end

        missing = Set[]
        broken = Set[]
        outdated = Set[]

        check_dep(pkgbase) do |dep, type|
            dep = dep.split(/[<>=]/)[0]

            if ! $rv_provides.include?(dep) && ! $x86_depnames_by_pkgbase[pkgbase].include?(dep)
                missing << [dep, type]
            elsif $broken_pkgnames.include?(dep)
                broken << [dep, type]
            elsif $version_mismatch_pkgnames.include?(dep)
                outdated << [dep, type]
            end
        end
        
        return missing, broken, outdated
    end

    def dep_anchor(depname)
        $x86_pkgbase_by_depname[depname] || depname
    end

    def make_link(list, pkg)
        package, type = pkg
        type = type ? "&nbsp;(#{type})" : ""
        anchor = dep_anchor(package)
        list ? "<li><a href='##{anchor}'>#{package}</a>#{type}</li>" : "<a href='##{anchor}'>#{package}</a>#{type}"
    end

    def make_tag_with_details(pkg_set, label, category)
        def get_config(pkg_set)
            # config: use_list, separator, content_before, content_after
            if pkg_set.size < 3
                return false, ', ', '', ''
            else
                return true, '', '<details><ul>', '</ul></details>'
            end
        end

        use_list, separator, content_before, content_after = get_config(pkg_set)
        " <span class='tag tag-with-details is-#{category}'>
          #{label}: #{content_before}#{pkg_set.map{|pkg| make_link(use_list, pkg)}.join(separator)}
          #{content_after}</span>"
    end
        
    def render_missing_dep(pkgbase, show_leaf=false)
        verstr = ""
        missing, broken, outdated = missing_dep(pkgbase)

        verstr += make_tag_with_details(missing, 'DEP MISSING', 'danger') if missing.any?
        verstr += make_tag_with_details(broken, 'DEP BROKEN', 'danger') if broken.any?
        verstr += make_tag_with_details(outdated, 'DEP OUTDATED', 'warning') if outdated.any?

        verstr += "Leaf package, port it!" if show_leaf and verstr.empty?
        verstr += " <a href='logs/#{pkgbase}/'><span class='tag is-text-invert'>Outdated FTBFS Logs</span></a>" if $outdated_log_pkgbases.include?(pkgbase)
        verstr
    end

    def melon_mark(name)
        result = ""
        if $marks.has_key? name
            $marks[name]["marks"].map do |mark|
                title = mark["comment"] + " by " + mark["by"]["alias"]
                case mark["name"]
                when "upstreamed"
                    result += " <a href='#{mark["comment"].split[0]}'><span title='#{title}' class='tag is-success'>Upstreamed</span></a>"
                when "stuck"
                    result += " <span class='tag is-danger' title='#{title}'>Stuck</span>"
                when "ready"
                    result += " <span class='tag is-success' title='#{title}'>Ready</span>"
                when "failing"
                else
                    result += " <span class='tag is-text-invert' title='#{title}'>#{mark["name"]}</span>"
                end
            end
        end
        result
    end

    def representative_x86_package(pkgbase)
        pkgnames = $x86_pkgnames_by_pkgbase[pkgbase].select{|pkgname| $x86_packages.has_key? pkgname}.sort
        pkgname = pkgnames.include?(pkgbase) ? pkgbase : pkgnames.first
        return nil, nil if ! pkgname

        [pkgname, $x86_packages[pkgname]]
    end

    def version_mismatch_pkgname(pkgbase)
        $x86_pkgnames_by_pkgbase[pkgbase].sort.find do |pkgname|
            $version_mismatch_pkgnames.include?(pkgname) && $rv_packages.has_key?(pkgname)
        end
    end

    puts "Checking FTBFS logs..."
    ($broken_pkgbases | $nocheck_pkgbases).sort.each do |pkgbase|
        _pkgname, package = representative_x86_package(pkgbase)
        next if ! package
        log_marks = ""
        ftbfs_link = "logs/#{pkgbase}/"
        log_marks += "<a href='#{ftbfs_link}'><span class='tag is-danger'>FTBFS</span></a>" if $broken_pkgbases.include? pkgbase
        log_marks += melon_mark(pkgbase) + render_missing_dep(pkgbase)
        if File.exist?("#{REPOROOT}/.status/logs/#{pkgbase}/#{pkgbase}-#{package['version']}.log")
            ftbfs_link = "logs/#{pkgbase}/#{pkgbase}-#{package['version']}.log"
            if File.mtime("#{REPOROOT}/.status/logs/#{pkgbase}/#{pkgbase}-#{package['version']}.log") < old_log_threshold
                log_marks += " <span class='tag is-warning'>old</span>"
            end
            failed_stage = parse_build_log("#{REPOROOT}/.status/logs/#{pkgbase}/#{pkgbase}-#{package['version']}.log")
            log_marks += " <span class='tag is-danger'>#{failed_stage}</span>" if failed_stage
        elsif Dir.glob("#{REPOROOT}/.status/logs/#{pkgbase}/#{pkgbase}-#{package['version']}-*.log").any?
            log_marks += " <span class='tag is-warning'>old format</span>"
        end

        if $nocheck_pkgbases.include?(pkgbase)
            log_marks += " " if ! log_marks.empty?
            log_marks += "<a href='#{ftbfs_link}'><span class='tag is-warning'>nochecked</span></a>"
        end

        id_str = ""
        id_str = "id='#{pkgbase}'" if $broken_pkgbases.include? pkgbase

        f.puts("<tr #{id_str}><td>#{package['db']}</td><td>#{pkgbase}</td><td>#{log_marks + patch_repo_link(pkgbase)}</td></tr>")
    end

    puts "Rendering version mismatch..."
    $version_mismatch_pkgbases.sort.each do |pkgbase|
        next if $broken_pkgbases.include? pkgbase
        pkgname = version_mismatch_pkgname(pkgbase)
        next if ! pkgname

        db = $x86_packages[pkgname]['db']
        rvver = $rv_packages[pkgname]["version"]
        x86ver = $x86_packages[pkgname]['version']

        cmp = pyalpm.vercmp(rvver, x86ver)
        if cmp < 0
            rvpkgver = rvver.split("-")[0]
            x86pkgver = x86ver.split("-")[0]
            if rvpkgver == x86pkgver
                rvpkgrel = rvver.split("-")[1]
                x86pkgrel = x86ver.split("-")[1]
                verstr = "#{rvpkgver}-<span style='color:var(--bulma-success)'>#{rvpkgrel} -> </span>#{x86pkgver}-<span style='color:var(--bulma-success)'>#{x86pkgrel}</span>"
            else
                verstr = "<span style='color:var(--bulma-success)'>#{rvver} -> #{x86ver}</span>"
            end
        elsif cmp > 0
            verstr = "<span style='color:var(--bulma-warning)'>#{rvver} <- #{x86ver}</span>"
        else
            verstr = "<span style='color:var(--bulma-danger)'>#{rvver} == #{x86ver}</span>"
        end

        from_tag = arch_gitlab_tag(rvver)
        to_tag = arch_gitlab_tag(x86ver)
        compare_url = arch_gitlab_compare_url(pkgbase, rvver, x86ver)
        verstr += " <span class='tag tag-with-details is-dark commit-loader' hx-get='#{ERB::Util.html_escape(compare_url)}' hx-trigger='click once' hx-swap='none' title='Load commits from #{ERB::Util.html_escape(from_tag)} to #{ERB::Util.html_escape(to_tag)}'>Changes</span>"

        verstr += melon_mark(pkgbase) + render_missing_dep(pkgbase)

        verstr += patch_repo_link(pkgbase)

        if $nocheck_pkgbases.include?(pkgbase)
            verstr += " <span class='tag is-warning'>nochecked</span>"
        end

        f.puts("<tr id='#{pkgbase}'><td>#{db}</td><td>#{pkgbase}</td><td>#{verstr}</td></tr>")
    end

    puts "Rendering missing packages..."
    missing_pkgbases = Set[]
    $x86_packages.each do |pkgname, package|
        pkgbase = package['base']
        next if $rv_packages.include? pkgname or $broken_pkgbases.include? pkgbase
        next if $current_rv_package_mtimes_by_pkgbase[pkgbase].any?
        next if $blacklist.include? pkgbase or $blacklist.include? pkgname

        missing_pkgbases << pkgbase
    end

    missing_pkgbases.each do |pkgbase|
        _pkgname, package = representative_x86_package(pkgbase)
        next if ! package

        verstr = melon_mark(pkgbase) + render_missing_dep(pkgbase, show_leaf=true)
        verstr += patch_repo_link(pkgbase)
        f.puts("<tr id='#{pkgbase}'><td>#{package['db']}</td><td>#{pkgbase}</td><td>#{verstr}</td></tr>")
    end

    puts "Rendering lint..."
    lint_by_pkgbase = Hash.new do |h,k|
        h[k] = {
            "db" => nil,
            "missing" => [],
            "wrong_db" => Hash.new{|repo_h, repo| repo_h[repo] = []},
        }
    end
    $rv_packages.each do |pkgname, package|
        pkgbase = package['base']
        lint_by_pkgbase[pkgbase]["db"] ||= package['db']
        if ! $x86_packages.include? pkgname
            lint_by_pkgbase[pkgbase]["missing"] << pkgname
        elsif $x86_packages[pkgname]["db"] != package["db"]
            lint_by_pkgbase[pkgbase]["wrong_db"][$x86_packages[pkgname]["db"]] << pkgname
        end
    end

    lint_by_pkgbase.each do |pkgbase, lint|
        messages = []
        if lint["missing"].any?
            packages = lint["missing"].map do |pkgname|
                depnames = [pkgname] + $rv_packages[pkgname]["provides"].map{|_package| _package.split(/[<>=]/)[0]}
                required_by = depnames.flat_map{|depname| $rv_required_by_depname[depname].to_a}.uniq - [pkgname]
                required_by_links = required_by.map{|required_by_pkgname| "<a href='##{$rv_packages[required_by_pkgname]["base"]}'>#{required_by_pkgname}</a>"}
                required_by.empty? ? pkgname : "#{pkgname} (required by #{required_by_links.join(", ")})"
            end.join(", ")
            subject = lint["missing"].size == 1 ? "package" : "packages"
            messages << "<span style='color:var(--bulma-warning)'>Lint: #{subject} not found in x86 repository: #{packages}.</span>"
        end
        lint["wrong_db"].each do |db, pkgnames|
            packages = pkgnames.join(", ")
            subject = pkgnames.size == 1 ? "package" : "packages"
            messages << "<span style='color:var(--bulma-danger)'>Lint: #{subject} in different x86 repository (#{db}): #{packages}.</span>"
        end
        next if messages.empty?

        f.puts("<tr><td>#{lint["db"]}</td><td>#{pkgbase}</td><td>#{messages.join(" ")}</td></tr>")
    end

    f.puts('</tbody></table>')
end

File.rename("#{REPOROOT}/.status/status.htm.tmp", "#{REPOROOT}/.status/status.htm")

puts "Updating lastupdate.txt and latestlogs.txt..."
`cd #{REPOROOT}/; find . -name '*.tar.zst' -type f -printf "%T@ %TF %TT %p\n" | sort -k1nr | head -n 10 | cut -d " " -f 2-4 > .status/lastupdate.txt`
`cd #{REPOROOT}/; find . -name '*.log' -type f -printf "%T@ %TF %TT %p\n" | sort -k1nr | head -n 50 | cut -d " " -f 2-4 > .status/latestlogs.txt`
